[features]
seeds = false
skip-lint = false
[programs.localnet]
vault = "7oh6tTdSfoWdKgqFXotGtPfS3Gqk6Jwc2yDZ7NCErYLW"
pool_weighted = "GfVXtcDC2vUReYr2kNsijGgvNjqhpnfCce5AnriQQvg4"
pool_stable = "CKZnJGq6aCDBccaoZUJkJpgYUVLpoVT51RfYpaMXP37f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
