[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.17"
package_manager = "yarn"

[features]
resolution = false
skip-lint = false

[programs.localnet]
stable_swap = "swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ"
weighted_swap = "swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW"
vault = "vo1tWgqZMjG61Z2T9qUaMYKqZ75CYzMuaZ2LZP1n7HV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".keypair/admin.json"

[workspace]
types = "packages/sdk/src/generated/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"
