[features]
seeds = false
skip-lint = false
[programs.localnet]
vault = "359c376ustKUBAy8ZJdjyRub9Kf7W4LHxxahXP8P9LEW"
pool_weighted = "7qmGmnrVnCjEjTnyxnCYJcraarutuX7Dsw3Wt5LU7ree"
pool_stable = "99TTqzz6CLm1NNjUAbvePk9L2FHSrht53RVaZCWCLryE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
